language: elixir
elixir:
  - 1.3.2
  - 1.4.1
otp_release:
  - 18.3
  - 19.0
matrix:
  allow_failures:
    - elixir: 1.3.2
      otp_release: 18.3
    - elixir: 1.3.2
      otp_release: 19.0    
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"